#!/bin/sh
# We pass in ratchetFrom here to ensure that we only format the files that have changed since the last commit
if command -v gradle >/dev/null 2>&1; then   # Check if gradle command exists to support GitHub Desktop on Windows
  gradle spotlessApply -PratchetFrom=HEAD -q # Requires Gradle to be installed
else
  ./gradlew spotlessApply -PratchetFrom=HEAD -q # Otherwise call gradle wrapper for Mac-OS / Unix / Git for Windows
fi
